<?php

namespace App\Http\Controllers\Api\V1\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Auth\Events\Verified;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Symfony\Component\HttpFoundation\Response;

/**
 * Handles the signed email-verification link generated by Laravel's built-in
 * `Illuminate\Auth\Notifications\VerifyEmail` notification.
 *
 * This does NOT change existing login/register behaviour. No route uses the
 * `verified` middleware, so accounts that never click the link can still log
 * in — this only lets a student mark their email as verified if they want to.
 */
class EmailVerificationController extends Controller
{
    /**
     * GET /v1/auth/email/verify/{id}/{hash} (signed URL, emailed to the user)
     */
    public function verify(Request $request, int $id, string $hash): JsonResponse|\Illuminate\Http\RedirectResponse
    {
        $user = User::query()->findOrFail($id);

        if (! hash_equals($hash, sha1($user->getEmailForVerification()))) {
            return response()->json(['message' => 'Invalid verification link.'], Response::HTTP_FORBIDDEN);
        }

        if (! $user->hasVerifiedEmail()) {
            $user->markEmailAsVerified();
            event(new Verified($user));
        }

        $frontendUrl = rtrim((string) env('FRONTEND_URL', config('app.url')), '/');

        return Redirect::away($frontendUrl.'/login?verified=1');
    }

    /**
     * POST /v1/auth/email/verification-notification (authenticated student re-requests the email)
     */
    public function resend(Request $request): JsonResponse
    {
        $user = $request->user();

        if ($user->hasVerifiedEmail()) {
            return response()->json(['message' => 'Email already verified.']);
        }

        $user->sendEmailVerificationNotification();

        return response()->json(['message' => 'Verification link sent.']);
    }

    /**
     * POST /v1/auth/email/resend (PUBLIC — by email, no auth required)
     *
     * Unverified users never receive an API token (register() and login()
     * both withhold it until the email is verified), so the authenticated
     * resend() endpoint above is unreachable for exactly the people who
     * need it. This endpoint lets the "Resend verification email" button
     * on the register/login pages work without a token, identifying the
     * account by email instead.
     *
     * Always returns the same generic message regardless of whether the
     * email exists, to avoid leaking which addresses are registered.
     */
    public function resendPublic(Request $request): JsonResponse
    {
        $request->validate([
            'email' => ['required', 'email'],
        ]);

        $user = User::query()->where('email', $request->string('email')->toString())->first();

        if ($user && ! $user->hasVerifiedEmail()) {
            $user->sendEmailVerificationNotification();
        }

        return response()->json([
            'message' => 'If an account with that email exists and is not yet verified, a new verification link has been sent.',
        ]);
    }
}
