<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Expand the preferred_degree enum to include all degree types
     * sent by the Recommendation Wizard frontend:
     *   mba, bachelor_arts, bachelor_eng, master_arts, master_eng
     *
     * PostgreSQL does not support ALTER COLUMN … TYPE enum(…) directly,
     * so we drop the old check constraint and add a new one via raw SQL.
     */
    public function up(): void
    {
        // Drop the old check constraint generated by Laravel's enum()
        DB::statement('ALTER TABLE student_profiles DROP CONSTRAINT IF EXISTS student_profiles_preferred_degree_check');

        // Add the updated check constraint with the full value list
        DB::statement("
            ALTER TABLE student_profiles
            ADD CONSTRAINT student_profiles_preferred_degree_check
            CHECK (preferred_degree IN (
                'bachelor', 'bachelor_arts', 'bachelor_eng',
                'master', 'master_arts', 'master_eng',
                'mba',
                'phd'
            ))
        ");
    }

    public function down(): void
    {
        // Revert to the original three-value constraint
        DB::statement('ALTER TABLE student_profiles DROP CONSTRAINT IF EXISTS student_profiles_preferred_degree_check');

        DB::statement("
            ALTER TABLE student_profiles
            ADD CONSTRAINT student_profiles_preferred_degree_check
            CHECK (preferred_degree IN ('bachelor', 'master', 'phd'))
        ");
    }
};
